class CalorieModel(BaseModel):
    TABLE = 'calorie_logs'
    @classmethod
    def log(cls, uid, date, calories, goal): ...
    @classmethod
    def today(cls, uid, date): ...
    @classmethod
    def range(cls, uid, start, end): ...
