class MacroTargetModel(BaseModel):
    TABLE = 'macro_targets'
    @classmethod
    def get(cls, uid, target_date): ...
    @classmethod
    def save(cls, uid, target_date, protein, carbs, fat, calories): ...
    @classmethod
    def history(cls, uid, limit=30): ...
